spring.batch.initialize-schema: always
broker.url: tcp://localhost:61616
#spring.activemq.in-memory: true
kohls.users.queue: users.Q
spring.activemq.pooled: false
spring.datasource.url: jdbc:mysql://localhost/KOHLS?autoReconnect=true&useSSL=false&relaxAutoCommit=true
spring.datasource.username: kohls
spring.datasource.password: p@ssw0rd
spring.datasource.continueOnError: false
spring.batch.databaseType: MYSQL
spring.batch.databaseSchema: KOHLS
jms.receive.timeout: 10000
chunk.size: 1000
max.threads: 10
spring.batch.job.enabled: false
barcode.service.url: http://10.0.1.177:8090/activateBarcode/
spring.batch.database.read.statement: SELECT ID, EVENT_ID, LOYALTY_ACCOUNT_EMAIL, REWARD_DOLLAR_AMOUNT, REWARD_VALUE, STATUS FROM LOYALTY_ACCOUNTS WHERE  STATUS = 'NEW'
spring.batch.database.insert.statement: INSERT INTO LOYALTY_BARCODE(ID, LOYALTY_ACCOUNT_EMAIL, BARCODE, PIN) values(?, ?, ?, ?)
spring.batch.database.update.statement: UPDATE LOYALTY_ACCOUNTS SET STATUS = ? WHERE ID = ?